// import { test, expect } from '@playwright/test';

// test('test', async ({ page }) => {
//   await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login');
//   await page.getByRole('textbox', { name: 'Username' }).click();
//   await page.getByRole('textbox', { name: 'Username' }).fill('Admin');
//   await page.getByRole('textbox', { name: 'Password' }).click();
//   await page.getByRole('textbox', { name: 'Password' }).fill('admin123');
//   await page.getByRole('button', { name: 'Login' }).click();
//   await page.getByRole('link', { name: 'Recruitment' }).click();
//   await page.locator('.oxd-icon.bi-caret-down-fill.oxd-select-text--arrow').first().click();
//   await page.getByRole('option', { name: 'Account Assistant' }).click();
//   await page.locator('div:nth-child(2) > .oxd-input-group > div:nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text--after > .oxd-icon').click();
//   await page.getByRole('option', { name: 'Junior Account Assistant' }).click();
//   await page.locator('div:nth-child(3) > .oxd-input-group > div:nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text--after > .oxd-icon').click();
//   await page.getByRole('listbox').getByText('Salvatore Davis-Quitzon').click();
//   await page.locator('div:nth-child(4) > .oxd-input-group > div:nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text--after > .oxd-icon').click();
//   await page.getByRole('listbox').getByText('Application Initiated').click();
//   await page.getByRole('textbox', { name: 'Type for hints...' }).click();
//   await page.getByRole('textbox', { name: 'Type for hints...' }).fill('AD');
//   await page.getByRole('textbox', { name: 'Enter comma seperated words...' }).click();
//   await page.getByRole('textbox', { name: 'Enter comma seperated words...' }).fill('AD');
//   await page.locator('.oxd-icon.bi-calendar').first().click();
//   await page.getByText('8', { exact: true }).click();
//   await page.locator('div:nth-child(4) > .oxd-input-group > div:nth-child(2) > .oxd-date-wrapper > .oxd-date-input > .oxd-icon').click();
//   await page.getByText('9', { exact: true }).click();
//   await page.locator('div:nth-child(3) > .oxd-grid-4 > .oxd-grid-item > .oxd-input-group > div:nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text--after > .oxd-icon').click();
//   await page.getByRole('option', { name: 'Manual' }).click();
//   await page.getByRole('button', { name: 'Search' }).click();
//   await page.getByRole('button', { name: 'Search' }).click();
// });